Resolved indent problem in on-pr-resolved workflow again..

diff --git a/.github/workflows/on-pr-resolved.yml b/.github/workflows/on-pr-resolved.yml
--- a/.github/workflows/on-pr-resolved.yml
+++ b/.github/workflows/on-pr-resolved.yml
@@ -11,33 +11,33 @@ jobs:
     name: Create release tag
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Assign Git Commit Epoch to $GITHUB_OUTPUT
-        id: git_commit_epoch
-        run: echo "GIT_COMMIT_EPOCH=$(git show -s --format=%ct HEAD)" >> "$GITHUB_OUTPUT"
-      - name: Get the latest tag
-        id: get_tag
-        run: |
-          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
-          echo "Latest tag: $latest_tag"
-          echo "::set-output name=latest_tag::$latest_tag"
-      - name: Extract and increment the minor version
-        id: new_tag
-        run: |
-          latest_tag=${{ steps.get_tag.outputs.latest_tag }}
-          if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-            major=${BASH_REMATCH[1]}
-            minor=${BASH_REMATCH[2]}
-            patch=${BASH_REMATCH[3]}
-            new_minor=$((minor + 1))
-            TAG="v${major}.${new_minor}.${{ steps.git_commit_epoch.outputs.GIT_COMMIT_EPOCH }}"
-            echo "New tag: $TAG"
-            echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
-          else
-            echo "Error: Latest tag does not match the expected format"
-            exit 1
-          fi
+        - name: Checkout code
+          uses: actions/checkout@v3
+        - name: Assign Git Commit Epoch to $GITHUB_OUTPUT
+          id: git_commit_epoch
+          run: echo "GIT_COMMIT_EPOCH=$(git show -s --format=%ct HEAD)" >> "$GITHUB_OUTPUT"
+        - name: Get the latest tag
+          id: get_tag
+          run: |
+            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
+            echo "Latest tag: $latest_tag"
+            echo "::set-output name=latest_tag::$latest_tag"
+        - name: Extract and increment the minor version
+          id: new_tag
+          run: |
+            latest_tag=${{ steps.get_tag.outputs.latest_tag }}
+            if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+              major=${BASH_REMATCH[1]}
+              minor=${BASH_REMATCH[2]}
+              patch=${BASH_REMATCH[3]}
+              new_minor=$((minor + 1))
+              TAG="v${major}.${new_minor}.${{ steps.git_commit_epoch.outputs.GIT_COMMIT_EPOCH }}"
+              echo "New tag: $TAG"
+              echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
+            else
+              echo "Error: Latest tag does not match the expected format"
+              exit 1
+            fi
         - uses: actions/github-script@v5
           with:
             script: |
